

export const HREF_PREFIX = 'https://api.stormpath.com/v1/applications/'
export const APPLICATION_KEY_STORE_DEALS = 'wwopVKreLQC1ada5g6NnN'
export const ADMIN_ACCOUNT_API_ID = '3QIEZ7NIZZW2ZTSAYG2TT56WL' // Not account user id
export const ADMIN_ACCOUNT_API_SECRET = 'rQD9KV8AX4gjWk77Xg4cqTTsQ1XhhHBqcKPcx7erYIg'

export const ADMIN_API_AUTH_KEY = ADMIN_ACCOUNT_API_ID + ':' + ADMIN_ACCOUNT_API_SECRET
export const ADMIN_API_AUTH_KEY_BASE64_ENCODED = 'M1FJRVo3TklaWlcyWlRTQVlHMlRUNTZXTDpyUUQ5S1Y4QVg0Z2pXazc3WGc0Y3FUVHNRMVhoaEhCcWNLUGN4N2VyWUln'

// urls
export const URL_REGISTER_NEW_USER = HREF_PREFIX + APPLICATION_KEY_STORE_DEALS + '/accounts'
export const URL_LOGIN_USER = HREF_PREFIX + APPLICATION_KEY_STORE_DEALS + '/loginAttempts'
export const URL_APPLICATION_HREF = HREF_PREFIX + APPLICATION_KEY_STORE_DEALS
